### ISSUE TITLE
Safety

### ISSUE THREAD

**Issue by EntroFlux** [shakalaca/MagiskOnEmulator#26]
Hi! I managed the install but s do fail safety net with latest...I am very interested in your work and would like to discuss...is that possible?

**Comment by justneedhelp** [comment]
It's very difficult to pass. I tried Android x86 VirtualBox with MagiskHide with both Magisk HideProps Conf and BusyBox hide modules... nothing works. Tried also Emulating (spoofing) device via changing props.. still fail. It seems like there are some triggers which SafetyNet API detects and fails passing. I don't have any idea is it poossible to pass SafetyNet on a VirtuaBox device (with AVD it's highly likely impossible at all). I think this should be a private conversation because Google tracks GitHub activities.

**Comment by EntroFlux** [comment]
how do we do that?

**Comment by EntroFlux** [comment]
https://discord.gg/zFkqqn4g8H

**Comment by justneedhelp** [comment]
https://github.com/shakalaca/MagiskOnEmulator/issues/24#issuecomment-791062570

**Comment by fusionneur** [comment]
@EntroFlux you migh refraing from promoting discord servers here..

**Comment by EntroFlux** [comment]
@fusionneur it was not my intent to promote....the matter of not talking openly here aroee.....that is the easiest place for me...it seems we hsve a common goal....also quite clear this is not my normal turf... somewhere in the middle then

**Comment by HemanthJabalpuri** [comment]
@justneedhelp
When I use HiddenCore Xposer module, Magisk shows SafetyNet passed. I don't know if it really passes or not(Pokémon Go fails to login with this).

Thanks

**Comment by rushi12565** [comment]
> @justneedhelp
> When I use HiddenCore Xposed module, Magisk shows SafetyNet passed. I don't know if it really passes or not(Pokémon Go fails to login with this).
> 
> Thanks

I have tried that method too, but when I try to check if I really pass safetynet which is via [this app](https://play.google.com/store/apps/details?id=org.freeandroidtools.safetynettest) ,it failed, passing safetynet was not possible.

**Comment by shakalaca** [comment]
I believe safetynet related topic is beyond this project
